### ISSUE TITLE
Callback for empty stack?

### ISSUE THREAD

**Issue by subhendukundu** [HeavenOSK/flutter_swipable_stack#12]
It should have a mechanism to pull more data to fill the stack once the stack is empty.
Like pagination.

**Comment by HeavenOSK** [comment]
@subhendukundu 
Thanks for your suggestion. 
 
I think we can implement pagination by checking [SwipeableController#currnetIndex](https://pub.dev/documentation/swipable_stack/latest/swipable_stack/SwipeableStackController/currentIndex.html). 
SwipeableController exntends ChangeNotifier, so we can listen to it. When currentIndex is over the length of the items, we'll load additional items like followings:

```dart
  @override
  void initState() {
    super.initState();
    _items.addAll(_images);
    _controller = SwipeableStackController()
      ..addListener(() {
        if (_items.length - 1 <= _controller.currentIndex) {
          _items.addAll(_images);
        }
        setState(() {});
      });
  }
```

Full code is [here](https://gist.github.com/HeavenOSK/aafe736d18d085b5ce463419478cad4e#file-swipable_stack_pagination-dart-L52).

**Comment by subhendukundu** [comment]
Interesting! I am using `graphql`, so let me try this one if I can make it work. But super cool package. 🙏

**Comment by subhendukundu** [comment]
Also why aren't we fixing the typo? 🙈
`(Sorry, the package name swipable_stack is typo of swipeable stack)` Talking about this one.

**Comment by HeavenOSK** [comment]
We cannot change package name since we decided on `pub.dev` 😂

**Comment by subhendukundu** [comment]
Yup, how about just change 
```
SwipeableStack(
  builder: (context, index, constraints) {
    return Image.asset(imagePath);
  },
),
```
to 
```
SwipableStack(
  builder: (context, index, constraints) {
    return Image.asset(imagePath);
  },
),
```

Just for consistency! People give cool names all the time to packages. So I dont mind changing it to that. 😝

**Comment by HeavenOSK** [comment]
> Just for consistency! People give cool names all the time to packages. So I dont mind changing it to that. 😝
 
Nice suggestion! I agree with you.
  
I'll change that in the next version (from `SwipeableStack ` to `SwipableStack `). 
Thank you so much.
 
Of corse you are very welcome to make Pull Request 🙆‍♂️

**Comment by subhendukundu** [comment]
Well I like your solution. But there was a small issue.

```
class _MyHomePageState extends State<MyHomePage> {
  List<Post> posts;
  Function onFetchMore;
  SwipeableStackController _controller;

  @override
  void initState() {
    super.initState();
    posts = widget.posts;
    onFetchMore = widget.onFetchMore;
    _controller = SwipeableStackController()
      ..addListener(() {
        if (posts.length - 1 <= _controller.currentIndex) {
         // to fetch more data from Graphql, I had to pass a method from the parent to this child.
          onFetchMore();
        }
      });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: _buildAppBar(),
      body: Center(
        child: Container(
          constraints: BoxConstraints(
            minWidth: 300,
            maxWidth: 500,
            maxHeight: 730,
          ),
          padding: EdgeInsets.all(10),
          child: SwipeableStack(
            controller: _controller,
            onSwipeCompleted: (index, direction) {
              print('$index, $direction');
            },
            builder: (context, index, constraints) {
              final Post post = posts[index];
              return ProfileCard(
                post: post,
              );
            },
            itemCount: posts.length,
          ),
        ),
      ),
      bottomNavigationBar: _buildBottomBar(),
    );
  }
}
```

Well it does fetch more data, but the small issue is, as I am getting the data to the `MyHomePage` component. But it does not create a new stack. Is it because of the prop changed but didnt rerended the `SwipeableStack`. Do I need to force render? How do I do that?

**Comment by subhendukundu** [comment]
Ignore this one. I assumed I had added `key: UniqueKey(),`.  🙈 My bad.
