### ISSUE TITLE
Allow multiple Rewind

### ISSUE THREAD

**Issue by SkylarMark** [HeavenOSK/flutter_swipable_stack#18]
Hey there I used the `rewind()` function to rewind to a previous card but it only goes 1 card back. How can I achieve more rewind. Currently using controller.currentIndex to set to previous card.

**Comment by sagar440** [comment]
Hi there, Could you please make this happen?

**Comment by HeavenOSK** [comment]
Thanks for you feedback.
 
I don't implement multiple card rewinding feature , this is because how we rewind depends largely on the design of our app's business.
For now, I’ve not come up with a interface design that can handle many use cases.

**Comment by SkylarMark** [comment]
ok, thank you
