### ISSUE TITLE
typo in changelog.md

### ISSUE THREAD

**Issue by kevsjh** [HeavenOSK/flutter_swipable_stack#30]
Hi @HeavenOSK 

First of, thanks for the mentioned. 

I noticed a typo in the changelog.md that is dropping the package points on pub.dev

![image](https://user-images.githubusercontent.com/66693290/137096345-0fe1de3a-196d-404d-ab34-1650fc355558.png)

**Comment by HeavenOSK** [comment]
@kevsjh 
Thanks for notifying it! 🙏 
 
I'll fix it on the next version!
