### ISSUE TITLE
how to stack card items of 3 or more at top

### ISSUE THREAD

**Issue by saginbajracharya** [HeavenOSK/flutter_swipable_stack#33]

**Comment by HeavenOSK** [comment]
@saginbajracharya 
There are no way now. I have made impossible to set stacking count to make implicit rule.

**Comment by saginbajracharya** [comment]
Ok thanks for the clarification

**Comment by riccardocescon** [comment]
Have you planned on stacking more than 3 items? There are different cases where you have more than 3 items to stack

**Comment by saginbajracharya** [comment]
Have you planned on stacking more than 3 items?-Yes I needed to show swipable cards with next items behind at top any number of cards so that user knows its swipable. There are different cases where you have more than 3 items to stack.-What I see possible is to stack behind fake cards but to show /un-show when item change is a hassle but possible. Sent from Mail for Windows From: Riccardo CesconSent: Sunday, January 23, 2022 7:06 PMTo: HeavenOSK/flutter_swipable_stackCc: sagin bajracharya; MentionSubject: Re: [HeavenOSK/flutter_swipable_stack] how to stack card items of 3 or more at top (Issue #33) Have you planned on stacking more than 3 items? There are different cases where you have more than 3 items to stack—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by HeavenOSK** [comment]
@saginbajracharya
Please add your formatted message 🙏

**Comment by riccardocescon** [comment]
> +Have you planned on stacking more than 3 items? -Yes I needed to show swipable cards with next items behind at top any number of cards so that user knows its swipable. +There are different cases where you have more than 3 items to stack. -What I see possible is to stack behind fake cards but to show /un-show when item change is a hassle but possible.

Yes that's what i did, i made 3 cards and simply change the UI on the "back" cards so it gives the impression to have multiple cards, that is why i have removed the question here. Thank you for the reply
