### ISSUE TITLE
Not able to swipe any cards if building inside FutureBuilder.

### ISSUE THREAD

**Issue by immutablesyntax** [HeavenOSK/flutter_swipable_stack#42]
If a build the SwipableStack inside FutureBuilder, I am not able to swipe the stack of individual widgets. The widgets to get rendered on screen but nothing happens if I try to drag them.

`Expanded(
          flex: 15,
          child: Padding(
            padding: const EdgeInsets.all(10.0),
            child: FutureBuilder(
              future: Provider.of<Property>(context, listen: false)
                  .fetchProperties(),
              builder: (ctx, snapShot) {
                if (snapShot.connectionState == ConnectionState.waiting) {
                  return Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      const CircularProgressIndicator(),
                    ],
                  );
                } else {
                  return Consumer<Property>(builder: (bldctx, data, child) {
                    return SwipableStack(
                        swipeAnchor: SwipeAnchor.bottom,
                        onSwipeCompleted: (index, direction) {
                          print('$index, $direction');
                        },
                        stackClipBehaviour: Clip.none,
                        onWillMoveNext: (index, direction) {
                          if (direction == SwipeDirection.up) {
                            showModalBottomSheet(
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(10.0),
                                ),
                                context: context,
                                builder: (ctx) {
                                  return Container(
                                    child: Center(
                                      child: Text('Dummy Text'),
                                    ),
                                  );
                                });
                          }
                          final allowedActions = [
                            SwipeDirection.right,
                            SwipeDirection.left,
                          ];
                          return allowedActions.contains(direction);
                        },
                        controller: _controller,
                        itemCount: data.properties.length,
                        builder: (ctxt, props) {
                          return ClipRRect(
                            borderRadius: BorderRadius.circular(8.0),
                            child:
                                data.properties[props.index].thumbnailId != null
                                    ? Image.network(
                                        '${CommonEndpoints.assetUrl}/${data.properties[props.index].thumbnailId!.files!.elementAt(0)}',
                                        fit: BoxFit.cover,
                                      )
                                    : null,
                          );
                        });
                  });
                }
              },
              // child: ,
            ),
          ),
        )`

The swipeable stack works if use List<Strings> made of imageUrls, but widgets is undraggable after async call.

**Comment by HeavenOSK** [comment]
@immutablesyntax 
Thanks for making this issue!
 
Can you provide a minimal example of how this problem can be reproduced?

**Comment by sameerkhan24** [comment]
@HeavenOSK the example you provided on pub.dev doesn't even call the swipable stack. I think you uploaded the wrong example there. Please provide an example that is using a list of widgets.
https://pub.dev/packages/swipable_stack/example

**Comment by HeavenOSK** [comment]
@sameerkhan24 
> the example you provided on pub.dev doesn't even call the swipable stack. 
 
It’s not related to this issue. I don’t agree with you.

**Comment by immutablesyntax** [comment]
Sorry for the delay. I tried to reproduce the issue this morning with the new version 1.2.0 of swipable_stack by creating a new project. The issue I mentioned is resolved now.

I went back to to my project did a flutter clean and upgraded to 1.2.0 and everything seems to be working now. 

Sorry if I did not explain my problem fully the first time.

Here is the code if anyone wants to reproduce the result.Here is the main.dart file code of the demo project.

Dependencies installed: provider, swipable_stack

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:swipable_stack/swipable_stack.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'SwipableStack Demo',
      theme: ThemeData(
        primarySwatch: Colors.blue,
      ),
      home: const MyHomePage(title: 'SwipableStack Demo'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);
  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  @override
  Widget build(BuildContext context) {
    return MultiProvider(
      providers: [ChangeNotifierProvider.value(value: Dummy())],
      child: Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
        ),
        body: Center(
          child: DummyScreen(),
        ),
      ),
    );
  }
}

class DummyScreen extends StatelessWidget {
  static const routeName = '/buyer-property-swiper';
  DummyScreen({Key? key}) : super(key: key);

  final _controller = SwipableStackController();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        body: SafeArea(
            child: Column(
      children: [
        const SizedBox(
          height: 5,
        ),
        Expanded(
          flex: 1,
          child: Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              TextButton(
                onPressed: () {
                  _controller.rewind();
                },
                child: const Icon(
                  Icons.undo,
                ),
                style: TextButton.styleFrom(
                  shape: const CircleBorder(),
                  fixedSize: const Size(50, 50),
                ),
              ),
              TextButton(
                onPressed: () {},
                child: const Icon(
                  Icons.tune,
                ),
                style: TextButton.styleFrom(
                  shape: const CircleBorder(),
                  fixedSize: const Size(50, 50),
                ),
              )
            ],
          ),
        ),
        Expanded(
          flex: 15,
          child: Padding(
            padding: const EdgeInsets.all(10.0),
            child: FutureBuilder(
              future:
                  Provider.of<Dummy>(context, listen: false).fetchProperties(),
              builder: (ctx, snapShot) {
                if (snapShot.connectionState == ConnectionState.waiting) {
                  return Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: const [
                      CircularProgressIndicator(),
                    ],
                  );
                } else {
                  return Consumer<Dummy>(builder: (bldctx, data, child) {
                    return data.data.isNotEmpty
                        ? SwipableStack(
                            swipeAnchor: SwipeAnchor.bottom,
                            onSwipeCompleted: (index, direction) {
                              print('$index, $direction');
                            },
                            stackClipBehaviour: Clip.none,
                            onWillMoveNext: (index, direction) {
                              if (direction == SwipeDirection.up) {
                                showModalBottomSheet(
                                    shape: RoundedRectangleBorder(
                                      borderRadius: BorderRadius.circular(10.0),
                                    ),
                                    context: context,
                                    builder: (ctx) {
                                      return const Center(
                                        child: Text('Dummy'),
                                      );
                                    });
                              }
                              final allowedActions = [
                                SwipeDirection.right,
                                SwipeDirection.left,
                              ];
                              return allowedActions.contains(direction);
                            },
                            controller: _controller,
                            itemCount: data.data.length,
                            builder: (ctxt, props) {
                              return ClipRRect(
                                borderRadius: BorderRadius.circular(15.0),
                                child: Image.network(
                                  data.data[props.index],
                                  fit: BoxFit.cover,
                                ),
                              );
                            })
                        : const CircularProgressIndicator();
                  });
                }
              },
              // child: ,
            ),
          ),
        ),
        const SizedBox(
          height: 20,
        )
      ],
    )));
  }
}

class Dummy with ChangeNotifier {
  List<String> _data = [];

  List<String> get data {
    return [..._data];
  }

  Future<void> fetchProperties({int page = 1}) async {
    List<String> dummydata = [];
    Future.delayed(const Duration(seconds: 2), () {
      try {
        for (var i = 0; i < 5; i++) {
          dummydata.add('https://picsum.photos/id/$i/200/300');
        }

        _data = dummydata;
        notifyListeners();
      } catch (error) {
        rethrow;
      }
    });
  }
}

```

**Comment by HeavenOSK** [comment]
@immutablesyntax
It's OK! Thanks for using it🙏
