### ISSUE TITLE
How to disable repeating stack items?

### ISSUE THREAD

**Issue by smartrk** [HeavenOSK/flutter_swipable_stack#44]
child: SwipableStack(
                              detectableSwipeDirections: const {
                                SwipeDirection.right,
                                SwipeDirection.left,
                                SwipeDirection.up,
                              },
                              controller: _controller,
                              stackClipBehaviour: Clip.none,
                              onSwipeCompleted: (index, direction) {
                                totalListCount = index;

                                if (direction == SwipeDirection.left) {

                                  Provider.of<UserStore>(context, listen: false)
                                      .updateForgroundImage(
                                          imagePath('crossblue'));
                                  reaction("dismiss", currentUser, index);
                                }
                                if (direction == SwipeDirection.right) {
                                  reaction("like", currentUser, index);
                                  Provider.of<UserStore>(context, listen: false)
                                      .updateForgroundImage(
                                          imagePath('heartred'));
                                }
                                if (direction == SwipeDirection.up) {
                                  Navigator.push(
                                      context,
                                      MaterialPageRoute(
                                          builder: (context) => UserProfile(
                                                userOrOther: true,
                                                user: currentUser,
                                              )));
                                }
                              },
                              horizontalSwipeThreshold: 0.8,
                              verticalSwipeThreshold: 0.8,
                              builder: (context, properties) {
                                // properties.constraints.
                                final itemIndex =
                                    properties.index % matchList.length;
                                listIndex = properties.index % matchList.length;

                                print(
                                    'itemCountController::${_controller.currentIndex}');

                                return (matchList.length > 0)
                                    ? Stack(
                                        children: [
                                          ExampleCard(
                                            list: matchList,
                                            userData: matchList[itemIndex],
                                            assetPath: matchList[itemIndex]
                                                .profile_picture,
                                            currentUser: currentUser,
                                          ),
                                          // more custom overlay possible than with overlayBuilder
                                          if (properties.stackIndex == 0 &&
                                              properties.direction != null)
                                            CardOverlay(
                                              swipeProgress:
                                                  properties.swipeProgress,
                                              direction: properties.direction,
                                            )
                                        ],
                                      )
                                    : Container();
                              },
                            ),
                        )
                        
                        

--------------------------------------------------------------------------------

reaction(String reaction, User opponent, int index) async {
    print(HelpingMethods().getChannelId(user.id, opponent.id));

    bool res = await Provider.of<UserStore>(context, listen: false)
        .sendReaction(context, reaction, opponent.id.toString());

    if (res) {
      Provider.of<UserStore>(context, listen: false).removeMatchAt(index);
    }

    Provider.of<UserStore>(context, listen: false).updateForgroundImage('');
  }

**Comment by HeavenOSK** [comment]
@smartrk 
Could you add an example code please?

**Comment by HeavenOSK** [comment]
@smartrk 
Sorry, too late 🙏 
 
You can specify stack items count by setting `itemCount` of `SwipableStack` like following.
  
```dart
SwipableStack(
  itemCount: 3,
),
```
