### ISSUE TITLE
Stuck on Splash Screen When Running in Release

### ISSUE THREAD

**Issue by biswa1751** [HeavenOSK/flutter_swipable_stack#47]
App gets stuck on splash Screen , means just showing a black screen. When added the package
Steps to reproduce
1. Create a App and add the flutter swipable stack dependencies
2. Run flutter run --relase It will work for only first time
3. RUn flutter run --release , it will show blank screen

**Comment by ashwanigarg** [comment]
@HeavenOSK  facing the same issue, is there any way to fix it?
