### ISSUE TITLE
Black screen in release mode

### ISSUE THREAD

**Issue by imcybergeek** [HeavenOSK/flutter_swipable_stack#54]
https://user-images.githubusercontent.com/65075504/169685227-311e2966-8d0a-4331-8115-db8c9236cdf5.mp4

To replicate this, run any app with swipable stack in release mode.

**Comment by imcybergeek** [comment]
https://user-images.githubusercontent.com/65075504/169686511-8b39e5e6-0080-41da-9b3b-e9a81a4f363b.mp4

Works consistently when used like this. What could be the issue?

**Comment by imcybergeek** [comment]
After some experimentation, I found that giving a 50ms delay or so fixes the issue, is it required to give such a delay or is there any other way? @HeavenOSK

**Comment by HeavenOSK** [comment]
I couldn't reproduce this problem.

**Comment by ashwanigarg** [comment]
facing the same issue, is there any way to fix it?
