### ISSUE TITLE
Swipe Animation lagging

### ISSUE THREAD

**Issue by thePlayer094** [HeavenOSK/flutter_swipable_stack#55]
Hi! Is there any chance that i can fix the lagging while user swiping? I think it is because of the animation or maybe the perfomance of the lib. Is there any way that i can solve this issue? Because this library is awesome, also unuseable because of the lagging(tearing). Thank you!

**Comment by Maikol1804** [comment]
I also had to face the same problem, I don't know if my card has a lot of components but the card has a huge lag. I thought that it was my app but at this moment I think is the library.

**Comment by ghost** [comment]
@Maikol1804  Try to show placeholder if the current stackIndex != 0 like this:

`
if (swipeProperty.stackIndex != 0) {
              return //Show placeholder here;
            } else {
              return //Show your card widget here
            }
`

It will be better, but not perfect. But way more better...

**Comment by HeavenOSK** [comment]
Thanks for reporting this issue. What version is the problem itself occurring from?
 
I would be happy to share reproduction project.
