### ISSUE TITLE
Grey screen in release

### ISSUE THREAD

**Issue by DhanrajNimbalkar** [HeavenOSK/flutter_swipable_stack#60]
When I run the project in debug mode it works fine but in release mode, it shows a grey screen as it looks in attached image
![image](https://user-images.githubusercontent.com/48564463/172902979-2c0806a4-1156-4c7d-bae4-a459e457973d.png)

**Comment by HeavenOSK** [comment]
I thin this problem is not related to the library.

**Comment by ashwanigarg** [comment]
facing the same issue, is there any way to fix it?
