### ISSUE TITLE
How possible to return back removed widget 

### ISSUE THREAD

**Issue by tazik561** [HeavenOSK/flutter_swipable_stack#61]
Hello, when we swap a widget and this widget removed, is it possible to widget back? like view pager , we can swap to right and see the new widget and after that, we can return to the old widget with a swap to left?
Which mean you see widget 1, 2, 3 by swap to right, Now by swap to left see widget 2

**Comment by HeavenOSK** [comment]
I think you should customize PageView in that situation. PageView's transition is so customizable.
 
The following article seems to be helpful.
https://medium.com/flutter-community/a-deep-dive-into-pageview-in-flutter-with-custom-transitions-581d9ea6dded
